# Generated by Django 4.2 on 2023-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_dispatchedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchedorder',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
