# Generated by Django 4.2 on 2023-04-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_user_delete_cashier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserApp',
        ),
    ]
