# Generated by Django 4.2 on 2023-04-29 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_initial'),
        ('accounts', '0005_usertype_delete_userapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
