# Generated by Django 4.2 on 2023-04-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
