# Generated by Django 4.2 on 2023-04-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_table_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
