# Generated by Django 4.2 on 2023-04-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
