# Generated by Django 4.2 on 2023-04-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_table_id_alter_table_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
